package exercises.enums;

import java.util.concurrent.ThreadLocalRandom;

/**
 * 100 Фамилий в алфавитном порядке.
 */
public enum LastName {
    ADAMS,
    ALLEN,
    ALVAREZ,
    ANDERSON,
    BAILEY,
    BAKER,
    BENNET,
    BROOKS,
    BROWN,
    CAMPBELL,
    CARTER,
    CASTILLO,
    CHAVEZ,
    CLARK,
    COLLINS,
    COOK,
    COOPER,
    COX,
    CRUZ,
    DAVIS,
    DIAZ,
    EDWARDS,
    EVANS,
    FLORES,
    FOSTER,
    GARCIA,
    GOMEZ,
    GONZALES,
    GRAY,
    GREEN,
    GUTIERREZ,
    HALL,
    HARRIS,
    HERNANDEZ,
    HILL,
    HOWARD,
    HUGHES,
    JACKSON,
    JAMES,
    JIMENEZ,
    JOHNSON,
    JONES,
    KELLY,
    KIM,
    KING,
    LEE,
    LEWIS,
    LONG,
    LOPEZ,
    MARTIN,
    MARTINEZ,
    MENDOZA,
    MILLER,
    MITCHELL,
    MOORE,
    MORALES,
    MORGAN,
    MORRIS,
    MURPHY,
    MYERS,
    NELSON,
    NGUYEN,
    ORTIZ,
    PARKER,
    PATEL,
    PEREZ,
    PETERSON,
    PHILLIPS,
    PRICE,
    RAMIREZ,
    RAMOS,
    REED,
    REYES,
    RICHARDSON,
    RIVERA,
    ROBERTS,
    ROBINSON,
    RODRIGUEZ,
    ROGERS,
    ROSS,
    RUIZ,
    SANCHEZ,
    SANDERS,
    SCOTT,
    SMITH,
    STEWART,
    TAYLOR,
    THOMAS,
    THOMPSON,
    TORRES,
    TURNER,
    WALKER,
    WARD,
    WATSON,
    WHITE,
    WILLIAMS,
    WILSON,
    WOOD,
    WRIGHT,
    YOUNG;

    private static final int LAST_NAMES_AMOUNT = LastName.values().length;

    public static String getRandomStringLastName() {
        return LastName.values()[ThreadLocalRandom.current()
                .nextInt(LAST_NAMES_AMOUNT)].toString();
    }

    public static LastName getRandomLastName() {
        return LastName.values()[ThreadLocalRandom.current()
                .nextInt(LAST_NAMES_AMOUNT)];
    }
}
