package exercises.enums;

import java.util.Arrays;
import java.util.Objects;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Top 100 tracks Billboard
 */
public enum Songs {
    TRACK_1("THE TWIST - Chubby Checker"),
    TRACK_2("SMOOTH - Santana Feat. Rob Thomas"),
    TRACK_3("MACK THE KNIFE - Bobby Darin"),
    TRACK_4("UPTOWN FUNK! - Mark Ronson Feat. Bruno Mars"),
    TRACK_5("HOW DO I LIVE - Leann Rimes"),
    TRACK_6("PARTY ROCK ANTHEM - LMFAO Feat. Lauren Bennett & GoonRock"),
    TRACK_7("I GOTTA FEELING - The Black Eyed Peas"),
    TRACK_8("MACARENA (BAYSIDE BOYS MIX) - Los Del Rio"),
    TRACK_9("SHAPE OF YOU - Ed Sheeran"),
    TRACK_10("PHYSICAL - Olivia Newton-John"),
    TRACK_11("YOU LIGHT UP MY LIFE - Debby Boone"),
    TRACK_12("HEY JUDE - The Beatles"),
    TRACK_13("CLOSER - The Chainsmokers Feat. Halsey"),
    TRACK_14("WE BELONG TOGETHER - Mariah Carey"),
    TRACK_15("UN-BREAK MY HEART - Toni Braxton"),
    TRACK_16("YEAH! - Usher Feat. Lil Jon & Ludacris"),
    TRACK_17("BETTE DAVIS EYES - Kim Carnes"),
    TRACK_18("ENDLESS LOVE - Diana Ross & Lionel Richie"),
    TRACK_19("TONIGHT’S THE NIGHT (GONNA BE ALRIGHT) - Rod Stewart"),
    TRACK_20("YOU WERE MEANT FOR ME/FOOLISH GAMES - Jewel"),
    TRACK_21("(EVERYTHING I DO) I DO IT FOR YOU - Bryan Adams"),
    TRACK_22("I’LL MAKE LOVE TO YOU - Boyz II Men"),
    TRACK_23("THE THEME FROM “A SUMMER PLACE” - Percy Faith & His Orchestra"),
    TRACK_24("LE FREAK - Chic"),
    TRACK_25("HOW DEEP IS YOUR LOVE - Bee Gees"),
    TRACK_26("EYE OF THE TIGER - Survivor"),
    TRACK_27("WE FOUND LOVE - Rihanna Feat. Calvin Harris"),
    TRACK_28("LOW - Flo Rida Feat. T-Pain"),
    TRACK_29("JUST WANT TO BE YOUR EVERYTHING - Andy Gibb"),
    TRACK_30("TOO CLOSE - Next"),
    TRACK_31("EVERY BREATH YOU TAKE - The Police"),
    TRACK_32("SOMEBODY THAT I USED TO KNOW - Gotye Feat. Kimbra"),
    TRACK_33("DESPACITO - Luis Fonsi & Daddy Yankee Feat. Justin Bieber"),
    TRACK_34("FLASHDANCE… WHAT A FEELING - Irene Cara"),
    TRACK_35("ROLLING IN THE DEEP - Adele"),
    TRACK_36("TOSSIN’ AND TURNIN’ - Bobby Lewis"),
    TRACK_37("THE BATTLE OF NEW ORLEANS - Johnny Horton"),
    TRACK_38("ONE SWEET DAY - Mariah Carey & Boyz II Men"),
    TRACK_39("TRULY MADLY DEEPLY - Savage Garden"),
    TRACK_40("SILLY LOVE SONGS - Wings"),
    TRACK_41("LET’S GET IT ON - Marvin Gaye"),
    TRACK_42("NIGHT FEVER - Bee Gees"),
    TRACK_43("ANOTHER ONE BITES THE DUST - Queen"),
    TRACK_44("SAY SAY SAY - Paul McCartney & Michael Jackson"),
    TRACK_45("HOW YOU REMIND ME - Nickelback"),
    TRACK_46("TIE A YELLOW RIBBON ROUND THE OLE OAK TREE - Dawn Feat. Tony Orlando"),
    TRACK_47("IT'S ALL IN THE GAME - Tommy Edwards"),
    TRACK_48("I WANT TO HOLD YOUR HAND - The Beatles"),
    TRACK_49("SHADOW DANCING - Andy Gibb"),
    TRACK_50("CALL ME MAYBE - Carly Rae Jepsen"),
    TRACK_51("BLURRED LINES - Robin Thicke Feat. T.I. + Pharrell"),
    TRACK_52("CANDLE IN THE WIND ‘97/SOMETHING ABOUT THE WAY YOU LOOK TONIGHT - Elton John"),
    TRACK_53("NO ONE - Alicia Keys"),
    TRACK_54("I WILL ALWAYS LOVE YOU - Whitney Houston"),
    TRACK_55("END OF THE ROAD - Boyz II Men"),
    TRACK_56("BOOM BOOM POW - The Black Eyed Peas"),
    TRACK_57("CALL ME - Blondie"),
    TRACK_58("LET ME LOVE YOU - Mario"),
    TRACK_59("STAYIN’ ALIVE - Bee Gees"),
    TRACK_60("LADY - Kenny Rogers"),
    TRACK_61("TIK TOK - KeSha"),
    TRACK_62("I’M A BELIEVER - The Monkees"),
    TRACK_63("GOLD DIGGER - Kanye West Feat. Jamie Foxx"),
    TRACK_64("APOLOGIZE - Timbaland Feat. OneRepublic"),
    TRACK_65("THE SIGN - Ace Of Base"),
    TRACK_66("CENTERFOLD - The J. Geils Band"),
    TRACK_67("ALL ABOUT THAT BASS - Meghan Trainor"),
    TRACK_68("(JUST LIKE) STARTING OVER - John Lennon"),
    TRACK_69("ROYALS - Lorde"),
    TRACK_70("THE BOY IS MINE - Brandy & Monica"),
    TRACK_71("BECAUSE I LOVE YOU (THE POSTMAN SONG) - Stevie B"),
    TRACK_72("I LOVE ROCK ’N ROLLN - Joan Jett & the Blackhearts"),
    TRACK_73("AQUARIUS/LET THE SUNSHINE IN - The 5th Dimension"),
    TRACK_74("WHOOMP! (THERE IT IS) - Tag Team"),
    TRACK_75("MOVES LIKE JAGGER - Maroon 5 Feat. Christina Aguilera"),
    TRACK_76("EBONY AND IVORY - Paul McCartney & Stevie Wonder"),
    TRACK_77("RUSH RUSH - Paula Abdul"),
    TRACK_78("THAT’S WHAT FRIENDS ARE FOR - Dionne & Friends (Stevie Wonder, Gladys Knight & Elton John)"),
    TRACK_79("HAPPY - Pharrell Williams"),
    TRACK_80("UPSIDE DOWN - Diana Ross"),
    TRACK_81("SUGAR, SUGAR - The Archies"),
    TRACK_82("JUST THE WAY YOU ARE - Bruno Mars"),
    TRACK_83("DILEMMA - Nelly Feat. Kelly Rowland"),
    TRACK_84("I HEARD IT THROUGH THE GRAPEVINE - Marvin Gaye"),
    TRACK_85("YOU’RE STILL THE ONE - Shania Twain"),
    TRACK_86("BILLIE JEAN - Michael Jackson"),
    TRACK_87("HOT STUFF - Donna Summer"),
    TRACK_88("ROCKSTAR - Post Malone Feat. 21 Savage"),
    TRACK_89("GANGSTA’S PARADISE - Coolio Feat. L.V."),
    TRACK_90("ABRACADABRA - The Steve Miller Band"),
    TRACK_91("PERFECT - Ed Sheeran"),
    TRACK_92("YOU’RE SO VAIN - Carly Simon"),
    TRACK_93("PLAY THAT FUNKY MUSIC - Wild Cherry"),
    TRACK_94("SAY YOU, SAY ME - Lionel Richie"),
    TRACK_95("MY SHARONA - The Knack"),
    TRACK_96("ALL NIGHT LONG (ALL NIGHT) - Lionel Richie"),
    TRACK_97("NOTHING COMPARES 2 U - Sinead O’Connor"),
    TRACK_98("I SWEAR - All-4-One"),
    TRACK_99("FAMILY AFFAIR - Mary J. Blige"),
    TRACK_100("WAITING FOR A GIRL LIKE YOU - Foreigner");

    private String value;

    Songs(String value) {
        this.value = value;
    }

    public static String getById(Integer number) {
        return Songs.values()[number].value;
    }
}
